### ISSUE TITLE
大佬你太屌了

### ISSUE THREAD

**Issue by DarkSand** [alisen39/TrWebOCR#10]
6666666666666666666666666666666666666666666666666666666

**Comment by alisen39** [comment]
哈哈  多谢多谢~能帮到忙就好

**Comment by rsqai** [comment]
大佬，这个是用的深度学习模型还是传统的手工设计模型

**Comment by rsqai** [comment]
> 大佬，这个是用的深度学习模型还是传统的手工设计模型

哦哦，看到了，用的crnn ctpn，这个能写个博客讲解一下原理嘛，简直太6了

**Comment by alisen39** [comment]
> 哦哦，看到了，用的crnn ctpn，这个能写个博客讲解一下原理嘛，简直太6了  

haha  这个我写不了，得看这个大佬的了[https://github.com/myhub/tr](https://github.com/myhub/tr)
