### ISSUE TITLE
繁体字无法识别

### ISSUE THREAD

**Issue by BleethNie** [alisen39/TrWebOCR#13]
如图，繁体字完全无法识别

![image](https://user-images.githubusercontent.com/17614992/84217511-efcfa780-aafe-11ea-8651-dac637b57140.png)

**Comment by BleethNie** [comment]
作者是否可以公开训练方法，或者如何上传训练集，我们想提交一些繁体训练集

**Comment by lewangdev** [comment]
可以试试 [PaddleWebOCR](https://github.com/lewangdev/PaddleWebOCR), 用 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) 简单替换了一下 tr，可以识别繁体字。

![image](https://user-images.githubusercontent.com/1455685/144066737-22a79010-4240-4c9d-8daa-6bc4842dcfa2.png)
