### ISSUE TITLE
Docker run

### ISSUE THREAD

**Issue by DreamlessRaw** [alisen39/TrWebOCR#20]
docker run -itd -p 8089:8089 --name trwebocr trwebocr:latest 运行错误
应该是：docker run -itd -p 8089:8089 --name trwebocr mmmz/trwebocr:latest
不然会找不到库
![image](https://user-images.githubusercontent.com/47837339/87214738-dd48c800-c361-11ea-8205-73c6a308a78f.png)

**Comment by alisen39** [comment]
没错，那条命令适用于build😂
