### ISSUE TITLE
怎么调用GPU版本？

### ISSUE THREAD

**Issue by yisampi** [alisen39/TrWebOCR#24]
怎么调用GPU版本？

**Comment by alisen39** [comment]
> 怎么调用GPU版本？
目前调用GPU版的需要部署在自己的服务器上，需要先安装CUDA 10.1以及cuDNN 7.6.5
可以直接通过命令行调用 python backend/main.py [--port=8089][--open_gpu=0]

**Comment by wycrystal** [comment]
> > 怎么调用GPU版本？
> 
> 目前调用GPU版的需要部署在自己的服务器上，需要先安装CUDA 10.1以及cuDNN 7.6.5
> 可以直接通过命令行调用 python backend/main.py [--port=8089][--open_gpu=0]

请问支持其它版本的CUDA吗？

**Comment by libinjale2008** [comment]
可以使用cuda11吗

**Comment by libinjale2008** [comment]
> > 怎么调用GPU版本？
> 
> 目前调用GPU版的需要部署在自己的服务器上，需要先安装CUDA 10.1以及cuDNN 7.6.5 可以直接通过命令行调用 python backend/main.py [--port=8089][--open_gpu=0]

可以使用cuda11吗
