### ISSUE TITLE
可否给出前端的源码

### ISSUE THREAD

**Issue by zouxiaoshi** [alisen39/TrWebOCR#26]
蛮不错的前端页面，所以想复用下，
发现前端代码是编译后的，
可否给出前端的源码，
多谢。

**Comment by alisen39** [comment]
谢谢喜欢~ 前端项目在 fontend 文件夹下

**Comment by wmh02240** [comment]
请教下右下角识别的文字区域的内容是怎么排序的啊？ @alisen39
