### ISSUE TITLE
CentOS8下安装，需要修改requirments.txt，取消指定的版本号

### ISSUE THREAD

**Issue by zhentg** [alisen39/TrWebOCR#3]
目前安装的软件版本如下，可以正常使用
pip list

Package        Version
-------------- -------------------
certifi        2020.4.5.1
libtorch       1.2.0.1
numpy          1.18.4
opencv-python  4.2.0.34
Pillow         7.1.2
pip            20.0.2
setuptools     46.1.3.post20200330
tornado        6.0.4
tr             1.0.0.3
wheel          0.34.2

**Comment by zhentg** [comment]
[requirements.new.txt](https://github.com/alisen39/TrWebOCR/files/4602474/requirements.new.txt)
附件是修改后的requirements.txt

**Comment by alisen39** [comment]
感谢，我有时间再在CentOS8下测试一下

**Comment by yuenshui** [comment]
尝试用楼上的方法，去掉版本号。还是有问题。
![image](https://user-images.githubusercontent.com/1950588/87215218-e38d7300-c366-11ea-92b5-f250aa0b8a1a.png)

**Comment by alisen39** [comment]
> 尝试用楼上的方法，去掉版本号。还是有问题。
> ![image](https://user-images.githubusercontent.com/1950588/87215218-e38d7300-c366-11ea-92b5-f250aa0b8a1a.png)

<img width="370" alt="图片" src="https://user-images.githubusercontent.com/34995117/87215350-75e24680-c368-11ea-85ee-1f5afb1d985e.png">
要先运行一下install.py哦
