### ISSUE TITLE
在特定压缩率下识别的时候有空值返回

### ISSUE THREAD

**Issue by y0baby** [alisen39/TrWebOCR#34]
在特定压缩率下识别的时候有空值返回，还有的时候识别出乱码。
![image](https://user-images.githubusercontent.com/71499828/93966576-9c285780-fd97-11ea-8a51-f876f651fcf8.png)

**Comment by YuLiu-lab** [comment]
我也遇到了这个问题，请问有解决办法吗？我本来测试的时候bmp是不会出现的，但当我并发的时候发现，bmp也会返回空值

**Comment by y0baby** [comment]
大部分情况下，更换一下压缩比率就可以识别正常了。













在 2021-09-22 13:26:51，"YuLiu" ***@***.***> 写道：

我也遇到了这个问题，请问有解决办法吗？我本来测试的时候bmp是不会出现的，但当我并发的时候发现，bmp也会返回空值

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YuLiu-lab** [comment]
> 大部分情况下，更换一下压缩比率就可以识别正常了。 在 2021-09-22 13:26:51，"YuLiu" ***@***.***> 写道： 我也遇到了这个问题，请问有解决办法吗？我本来测试的时候bmp是不会出现的，但当我并发的时候发现，bmp也会返回空值 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

好的，谢谢，我换过90，95，100的jpg，都会出现orz，可能是因为并发吧
