### ISSUE TITLE
大神，启动的时候需要连接哪个地址校验？我们需要针对性开个外网

### ISSUE THREAD

**Issue by 282066424** [alisen39/TrWebOCR#36]
大神，启动的时候需要连接哪个地址校验？我们需要针对性开个外网。如果要tr作者授权，需要怎么找到作者？

**Comment by alisen39** [comment]
anycode@yahoo.com  这个是tr作者的邮箱。在tr里面也可以看到~  https://github.com/myhub/tr

**Comment by k2361863478** [comment]
> [anycode@yahoo.com](mailto:anycode@yahoo.com) 这个是tr作者的邮箱。在tr里面也可以看到~ [https://github.com/myhub/tr。](https://github.com/myhub/tr%E3%80%82)
> 具体连接哪个地址可以直接联系作者问下

作者您好，可否有tr1.5对应的trwebocr地址呢

**Comment by k2361863478** [comment]
> 大神，启动的时候需要连接哪个地址校验？我们需要针对性开个外网。如果要tr作者授权，需要怎么找到作者？

好像是连接这个地址   tr-sdk-a.wilab.cn
