### ISSUE TITLE
麻烦问一下，raw_out 对象里面的字段都是什么意思？

### ISSUE THREAD

**Issue by SunGg12138** [alisen39/TrWebOCR#38]
![image](https://user-images.githubusercontent.com/16427275/96560779-4fca2c00-12f1-11eb-848e-fddc8961f948.png)

[40,70,14,19.14285659790039,0],"1",0.8767369985580444]

**Comment by SunGg12138** [comment]
能不能加上坐标信息，方便数据整合

**Comment by yyyear** [comment]
[40,70,14,19.14285659790039,0],"1",0.8767369985580444]
你好 . 你这个怎么关闭了  
[40,70,14,19.14285659790039,0] 这个数据 是位置信息吗 ,  怎么感觉 对不上

**Comment by yyyear** [comment]
> [40,70,14,19.14285659790039,0],"1",0.8767369985580444]
> 你好 . 你这个怎么关闭了
> [40,70,14,19.14285659790039,0] 这个数据 是位置信息吗 , 怎么感觉 对不上

看明白了  前面两个是文字的中心点   40,70 是x,y 的中间值
14, 19.14  是长和宽
