### ISSUE TITLE
为什么老是自动killed？

### ISSUE THREAD

**Issue by sangsxh** [alisen39/TrWebOCR#5]
我测试了下，服务启动，用着用着就自动杀掉了
centos 8 下启动的docker

每使用一次，内存好像没释放

**Comment by alisen39** [comment]
没释放的是加载的模型，建议你调大一点内存，或者将图片再压缩一下

**Comment by liba36** [comment]
请问这个模型全部加载完大概需要多大内存？

**Comment by alisen39** [comment]
> 请问这个模型全部加载完大概需要多大内存？ 

要占用大概1G的内存

**Comment by KDT-G** [comment]
> > 请问这个模型全部加载完大概需要多大内存？
> 
> 要占用大概1G的内存
我虚拟机设置了8g内存，外部调用接口进行识别，模型一直没有释放，没多久就占到7g多，这是怎么回事啊，有什么解决方法嘛，大佬

**Comment by yfq512** [comment]
我也会遇到这种情况，占用的显存一直升高，24g都用完了。我的解决方案是再写个脚本检测显存占用情况，一旦超了就kill掉再重新服务
