### ISSUE TITLE
postman调用接口报405: Method Not Allowed

### ISSUE THREAD

**Issue by DYJYZP** [alisen39/TrWebOCR#8]
大佬，
postman调用返回报错：
<html>
<title>405: Method Not Allowed</title>

<body>405: Method Not Allowed</body>

</html>
怎么解？用的是x-www-form-urlencoded模式，post方式调用

**Comment by alisen39** [comment]
直接使用form-data模式就好啦  
像这样：
![image](https://user-images.githubusercontent.com/34995117/82445873-2a35be00-9ad8-11ea-9387-d71f4419cd71.png)

**Comment by DYJYZP** [comment]
图片看不到（碎了），用form-data也报一样的错误

**Comment by alisen39** [comment]
那你再看一下 [接口文档](https://github.com/alisen39/TrWebOCR/wiki/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)，api调用要用POST方法哦

**Comment by fyzzz** [comment]
url最后要加上：/
