### ISSUE TITLE
使用ApiPost进行测试，无法使用API

### ISSUE THREAD

**Issue by MageMaize** [alisen39/TrWebOCR#80]
用ApiPost使用API，传入了对应的参数，返回405 Method Not Allowed  浏览器上就能用。明明提交的http头和post body都跟浏览器相同。electron使用axios也无法使用api

**Comment by MageMaize** [comment]
测试curl命令也无法使用
curl -F "file=@20211001192808.png" -F "compress=0" "http://10.10.1.2:8089/api/tr-run"
返回结果：
<html><title>405: Method Not Allowed</title><body>405: Method Not Allowed</body></html>

**Comment by alisen39** [comment]
要用POST方法哈~
