### ISSUE TITLE
跑一个小时，请求1000次之后，就识别不出来了

### ISSUE THREAD

**Issue by cijiahanjiang** [alisen39/TrWebOCR#85]
有没有大佬遇到这个情况，同样一张图片，跑上一段时间之后，就识别不出来了，是不是和自动更新有关。重启后正常，环境mac，使用docker安装

**Comment by Gxmg** [comment]
同样遇到问题，CPU一直处于很高的状态

**Comment by alisen39** [comment]
> 有没有大佬遇到这个情况，同样一张图片，跑上一段时间之后，就识别不出来了，是不是和自动更新有关。重启后正常，环境mac，使用docker安装

一直没有复现出来这个问题~  后续有考虑在接口里增加个缓存来优化这个问题
