### ISSUE TITLE
默认的8089跑起来了，但是想换其他端口应该怎么改

### ISSUE THREAD

**Issue by qq438633557** [alisen39/TrWebOCR#96]
run -itd --rm -p 8089:8089 --name trwebocr mmmz/trwebocr:latest

run -itd --rm -p 8888:888 --name trwebocr mmmz/trwebocr:latest

这样吗？改了其他端口就没法访问了 只有8089，求助

**Comment by alisen39** [comment]
姿势搞错了~~    -p <ip>:<host-port>:<container-port>   容器默认的是8089端口，所以你如果要改本机的映射那你可以改成 -p 8888:8089 这种
